return {
	"Bekaboo/dropbar.nvim",
	config = function()
		require("dropbar").setup({
			sources = {
				path = {
					max_depth = 1,
				},
				treesitter = {
					max_depth = 2,
					valid_types = {
						-- "block_mapping_pair",
						-- "array",
						-- "boolean",
						-- "break_statement",
						-- "call",
						-- "case_statement",
						"class",
						-- "constant",
						-- "constructor",
						-- "continue_statement",
						-- "delete",
						-- "do_statement",
						-- "element",
						-- "enum",
						-- "enum_member",
						-- "event",
						-- "for_statement",
						"function",
						-- "goto_statement",
						-- "if_statement",
						-- "interface",
						-- "keyword",
						-- "macro",
						"method",
						"namespace",
						-- "null",
						-- "number",
						-- "operator",
						-- "package",
						-- "pair",
						"property",
						-- "reference",
						-- "repeat",
						-- "return_statement",
						-- "rule",
						-- "rule_set",
						-- "scope",
						-- "section",
						-- "specifier",
						-- "struct",
						-- "switch_statement",
						-- "table",
						-- "type",
						-- "type_parameter",
						-- "unit",
						-- "value",
						-- "variable",
						-- "while_statement",
						"declaration",
						-- "field",
						-- "identifier",
						-- "object",
						-- "statement",
					},
				},
				lsp = {
					max_depth = 2,
					valid_symbols = {
						"File",
						"Module",
						"Namespace",
						"Package",
						"Class",
						"Method",
						"Property",
						"Field",
						"Constructor",
						"Enum",
						"Interface",
						"Function",
						-- "Variable",
						-- "Constant",
						-- "String",
						-- "Number",
						-- "Boolean",
						-- "Array",
						-- "Object",
						-- "Keyword",
						-- "Null",
						-- "EnumMember",
						-- "Struct",
						-- "Event",
						-- "Operator",
						-- "TypeParameter",
					},
				},
			},
		})

		local dropbar_api = require("dropbar.api")
		-- vim.keymap.set("n", ";", dropbar_api.pick, { desc = "Pick symbols in winbar" })
		-- vim.keymap.set("n", "[;", dropbar_api.goto_context_start, { desc = "Go to start of current context" })
		-- vim.keymap.set("n", "];", dropbar_api.select_next_context, { desc = "Select next context" })
	end,
}
